### ISSUE TITLE
Add ability to add custom styles

### ISSUE THREAD

**Issue by hashworks** [Stereobit/dragend#59]
Currently I need to override the inline styles set by dragend by `!important`:
```css
.dragend-page {
    height: auto !important;
    padding: $contentSpacing !important;
}
```

It would be great if I could set them as an option so I can avoid `!important`.
